WIDTH_WINDOW = 500
HEIGHT_WINDOW = 500

TITLE_WINDOW = "Banking"
SPLASHSCREEN_DELAY_SECONDS = 2

# User Login
TEXT_USER = "User"
TEXT_ADMINISTRATOR = "Administrator"

MODE_LOGIN = 1
MODE_ADD_USER_ADMINSTRATOR = 2
